In [2]:
import numpy as np
import torch
from torch import distributions

In [3]:
mu = torch.FloatTensor([[2,3,5],[2,3,5]])
sigma = torch.FloatTensor([[1,1,1],[1,1,1]])
weights = torch.FloatTensor([[0.33,0.33,0.34],[0.33,0.33,0.34]])

In [4]:
k = torch.multinomial(weights,num_samples=3,replacement=True)

In [5]:
k

tensor([[2, 1, 2],
        [1, 0, 2]])

In [6]:
torch.normal(mu,sigma)

tensor([[1.0755, 3.0750, 5.4765],
        [1.8220, 4.2122, 4.5775]])

In [7]:
a = np.zeros([3,3,6])

In [8]:
for _ in range(3):
    for __ in range(3):
        for ___ in range(6):
            a[_][__][___]=_*18+__*6+___

In [9]:
a[np.arange(3),k]

array([[[12., 13., 14., 15., 16., 17.],
        [24., 25., 26., 27., 28., 29.],
        [48., 49., 50., 51., 52., 53.]],

       [[ 6.,  7.,  8.,  9., 10., 11.],
        [18., 19., 20., 21., 22., 23.],
        [48., 49., 50., 51., 52., 53.]]])

In [10]:
a

array([[[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.]],

       [[18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.]],

       [[36., 37., 38., 39., 40., 41.],
        [42., 43., 44., 45., 46., 47.],
        [48., 49., 50., 51., 52., 53.]]])